---
- tasks:
    - name: wheel group exists
      group:
        name: wheel
        state: present

    - name: wheel group has passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%wheel"
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"

    - name: admin user exists
      user:
        name: "{{ admin_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: authorised key is set for remote user
      authorized_key:
        user: "{{ admin_user }}"
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
