---
- name: Install required system packages
  apt:
    name: "{{ system_packages }}"
    update_cache: true
    cache_valid_time: "3600"

- name: Upgrade all packages; autoremove & autoclean
  apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: "3600"
    autoremove: true
    autoclean: true
  notify: Reboot machine

- name: Generate SSH keys
  shell: ssh-keygen -f ~/.ssh/id_rsa -N ""
  args:
    creates: ~/.ssh/id_rsa

- name: Disable SSH PasswordAuthentication, PermitRootLogin, Port 22
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "sshd -t -f %s"
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^Port"
      line: "Port 22"
  notify: Restart ssh

- name: Limit SSH on UFW
  ufw:
    rule: limit
    name: OpenSSH

- name: Enable UFW, default policy deny incoming
  ufw:
    state: enabled
    policy: deny
    direction: incoming
    logging: "on"

- name: Enable unattended-upgrades
  template:
    src: "../templates/{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
